FROM node:18

WORKDIR /app

# Install dependencies early to cache better
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose Vite dev port
EXPOSE 5173

# Start Vite dev server with hot reload
CMD ["npm", "run", "dev"]
