
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - NEWSDATA_API_KEY=${NEWSDATA_API_KEY}
    depends_on:
      - db
      - qdrant  # ✅ added dependency

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: stockai
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  qdrant:  # ✅ renamed from vector-db to qdrant
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules  # prevents container from overwriting host node_modules
    ports:
      - "3000:3000"  # CRA or Vite default dev server port
    working_dir: /app
    command: npm run dev  # or `vite` depending on your project
    environment:
      - CHOKIDAR_USEPOLLING=true # 👈 ensures file watching works in Docker
    depends_on:
      - backend

volumes:
  pgdata:
  qdrant_data:
